services:
  morningandevening:
    build:
      context: .
      dockerfile: Dockerfile
    image: m_and_e-morningandevening:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - npm_default

networks:
  npm_default:
    external: true
